@startuml
class Factorial {
  +static int SolveFactorial(int n)
}
class ArrayMethods {
  +static int Sum(int[] array)
}
class Fibonacci {
  +static int GetFibonacci(int n)
}
class TreeNode<T> {
  +T Value
  +TreeNode<T> Left
  +TreeNode<T> Right
}
@enduml
