@startuml ExpressionEvaluatorService

interface IUndoStackRepository
interface IExpressionEvaluatorService
interface IExpressionValidator

abstract class Token
class NumberToken extends Token
class OperatorToken extends Token

class ExpressionEvaluatorService implements IExpressionEvaluatorService
class UndoStackRepository implements IUndoStackRepository
class ExpressionValidator implements IExpressionValidator

ExpressionEvaluatorService --> IUndoStackRepository
ExpressionEvaluatorService --> IExpressionValidator
UndoStackRepository --> Token

@enduml
