classDiagram
    class Box_T {
        +Box()
        +Item: T
    }
    class SafeBox_T {
        +SafeBox()
    }
    class Calculator_T {
        +Add()
        +Subtract()
        +Multiply()
        +Divide()
    }
    class Printer_T {
        +Print()
    }
    class Creator_T {
        +Create()
    }
    class IRepository_T {
        +Add()
        +Remove()
        +Get()
    }
    <<interface>> IRepository_T
